export const FETCH_COUNTRY_DATA_REQUEST = "FETCH_COUNTRY_DATA_REQUEST";
export const FETCH_COUNTRY_DATA_SUCCESS = "FETCH_COUNTRY_DATA_SUCCESS";
export const FETCH_COUNTRY_DATA_FAILURE = "FETCH_COUNTRY_DATA_FAILURE";

export const FETCH_FILTER_OPTIONS_REQUEST = "FETCH_FILTER_OPTIONS_REQUEST";
export const FETCH_FILTER_OPTIONS_SUCCESS = "FETCH_FILTER_OPTIONS_SUCCESS";
export const FETCH_FILTER_OPTIONS_FAILURE = "FETCH_FILTER_OPTIONS_FAILURE";

export const DETAILS_PAGE_REQUEST = "DETAILS_PAGE_REQUEST";
export const DETAILS_PAGE_SUCCESS = "DETAILS_PAGE_SUCCESS";
export const DETAILS_PAGE_FAILURE = "DETAILS_PAGE_FAILURE";

export const FETCH_SEARCH_RESULTS_REQUEST = "FETCH_SEARCH_RESULTS_REQUEST";
export const FETCH_SEARCH_RESULTS_SUCCESS = "FETCH_SEARCH_RESULTS_SUCCESS";
export const FETCH_SEARCH_RESULTS_FAILURE = "FETCH_SEARCH_RESULTS_FAILURE";
